"""Mongo collection name constants used across MCP tools."""


class Collections:
    PERSONNEL_MASTER = "personnel_master"
    ASSIGNMENT_MASTER = "assignment_master"
    UNIT = "unit_master"
    DISTRICT = "district_master"
    RANK_MASTER = "rank_master"
    DESIGNATION_MASTER = "designation_master"
    MANDAL = "mandal_master"
    UNIT_VILLAGES = "unit_villages_master"
    DEPARTMENT = "department_master"
    UNIT_TYPE = "unit_type_master"
    ROLES = "role_master"
    ROLES_MASTER = "roles_master"
    APPROVAL_FLOW_MASTER = "approval_flow_master"
    ERROR_MASTER = "error_master"
    LOG_MASTER = "log_master"
    MODULES_MASTER = "modules_master"
    NOTIFICATION_MASTER = "notification_master"
    PROMPT_MASTER = "prompt_master"
    VALUE_SETS_MASTER = "value_sets_master"
    JOBS_MASTER = "jobs_master"
    PERMISSIONS_MASTER = "permissions_master"
    PERMISSIONS_MAPPING_MASTER = "permissions_mapping_master"
    USER_ROLE_PERMISSIONS_MASTER = "user_role_permissions_master"
